FROM golang:1.19-alpine AS build-stage

WORKDIR /app
COPY . ./

WORKDIR /app/{{.ServiceDirectory}}
RUN go mod download

WORKDIR /app/libs/go/persistence/
RUN go mod download

WORKDIR /app
RUN CGO_ENABLED=0 \
  go build \
  -ldflags="-s -w" \
  -o /app/bin/service \
  /app/{{.ServiceDirectory}}/cmd/server/main.go

FROM scratch
COPY --from=build-stage /app/bin/service ./service
CMD ["./service"]
